#  iKuai Bypass 配置文件 大部分时候请使用默认设置即可
#  详情参考: https://github.com/joyanhui/ikuai-bypass
ikuai-url: http://192.168.9.1 # 爱快控制台地址，结尾不要加 "/"
username: admin # 爱快登陆用户名
password: admin888 # 爱快登陆密码
cron: 0 7 * * * # 更新周期cron表达式，例如 0 7 * * *
AddErrRetryWait: 10s # 自动重试时间间隔 (10s, 120s)
AddWait: 1s # 规则添加后的反应等待时间
github-proxy: "https://gh-proxy.com/" # Github代理加速地址，例如 https://gh-proxy.com/ (留空不使用)
custom-isp: # 自定义运营商分流 (IP分流)
  - name: 国内IP列表
    url: https://raw.githubusercontent.com/Loyalsoldier/geoip/release/text/cn.txt
    tag: ipcn # 规则TagName关键词（系统自动添加前缀 IKB）
  - name: telegram
    url: https://raw.githubusercontent.com/Loyalsoldier/geoip/release/text/telegram.txt
    tag: iptg # 规则TagName关键词（系统自动添加前缀 IKB）
  - name: google
    url: https://raw.githubusercontent.com/Loyalsoldier/geoip/release/text/google.txt
    tag: ipgoogle # 规则TagName关键词（系统自动添加前缀 IKB）
stream-domain: # 域名分流 (优先级高于IP分流)
  - interface: wan2 # 分流线路 (如 wan1)
    src-addr: 192.168.1.10-192.168.1.254 # 分流源地址 (IP或范围)
    src-addr-opt-ipgroup: "" # 分流源地址关联IP分组(用于匹配爱快中的IP分组 多个可以用逗号分割) 在设置了src-addr-opt-ipgroup后，src-addr参数会被忽略
    url: https://raw.githubusercontent.com/Loyalsoldier/v2ray-rules-dat/release/gfw.txt
    tag: gfw # 规则TagName关键词（系统自动添加前缀 IKB）
  - interface: wan2 # 分流线路 (如 wan1)
    src-addr: 192.168.1.10-192.168.1.254 # 分流源地址 (IP或范围)
    src-addr-opt-ipgroup: "" # 分流源地址关联IP分组(用于匹配爱快中的IP分组 多个可以用逗号分割) 在设置了src-addr-opt-ipgroup后，src-addr参数会被忽略
    url: https://raw.githubusercontent.com/joyanhui/ikuai-bypass/main/private/bypass-domain-list.txt
    tag: private_bypass # 规则TagName关键词（系统自动添加前缀 IKB）
  - interface: wan1 # 分流线路 (如 wan1)
    src-addr: 192.168.1.10-192.168.1.254 # 分流源地址 (IP或范围)
    src-addr-opt-ipgroup: "" # 分流源地址关联IP分组(用于匹配爱快中的IP分组 多个可以用逗号分割) 在设置了src-addr-opt-ipgroup后，src-addr参数会被忽略
    url: https://raw.githubusercontent.com/joyanhui/ikuai-bypass/main/private/direct-domain-list.txt
    tag: private_direct # 规则TagName关键词（系统自动添加前缀 IKB）
ip-group: # IP分组 (与端口分流配合使用)
  - name: 国内
    url: https://raw.githubusercontent.com/Loyalsoldier/geoip/release/text/cn.txt
  - name: Telegram
    url: https://raw.githubusercontent.com/Loyalsoldier/geoip/release/text/telegram.txt
ipv6-group: # IPv6分组 (与端口分流配合使用)
  - name: 国内v6
    url: https://raw.githubusercontent.com/Loyalsoldier/geoip/release/text/cn.txt
stream-ipport: # 端口分流 (下一跳网关/外网线路)
  - type: "0" # 分流方式：0-外网线路，1-下一跳网关
    opt-tagname: "国内流量" # 规则名称 (可选，如果没有则使用ip-group名称，如果两个都为空禁止启动)
    interface: wan1 # 分流线路 (如 wan1)
    nexthop: "" # 下一跳网关地址
    src-addr: 192.168.1.10-192.168.1.254 # 分流源地址 (IP或范围)
    src-addr-opt-ipgroup: "" # 分流源地址关联IP分组(用于匹配爱快中的IP分组 多个可以用逗号分割) 在设置了src-addr-opt-ipgroup后，src-addr参数会被忽略
    ip-group: 国内 # 关联的IP分组名称用于匹配爱快中的IP分组 多个可以用逗号分割)
    mode: 0 # 负载模式：0-新建连接数, 1-源IP, 2-源IP+源端口, 3-源IP+目的IP, 4-源IP+目的IP+目的端口, 5-主备模式
    ifaceband: 0 # 线路绑定：0-不勾选，1-勾选
  - type: "1" # 分流方式：0-外网线路，1-下一跳网关
    opt-tagname: "负责分流到下一跳" # 规则名称 (可选，如果没有则使用ip-group名称 ，如果两个都为空禁止启动)
    interface: "" # 分流线路 (如 wan1)
    nexthop: 192.168.1.2 # 下一跳网关地址
    src-addr: 192.168.1.10-192.168.1.254 # 分流源地址 (IP或范围)
    src-addr-opt-ipgroup: "" # 分流源地址关联IP分组(用于匹配爱快中的IP分组 多个可以用逗号分割) 在设置了src-addr-opt-ipgroup后，src-addr参数会被忽略
    ip-group: "Telegram" # 关联的IP分组名称用于匹配爱快中的IP分组 多个可以用逗号分割)
    mode: 0 # 负载模式：0-新建连接数, 1-源IP, 2-源IP+源端口, 3-源IP+目的IP, 4-源IP+目的IP+目的端口, 5-主备模式
    ifaceband: 0 # 线路绑定：0-不勾选，1-勾选
webui: # WebUI 管理服务设置
  port: "19000" # WebUI 服务端口
  user: admin # WebUI 用户名 (留空禁用认证)
  pass: admin888 # WebUI 密码
  enable: true # 是否启用 WebUI 服务
  enable-update: false # 是否启用配置文件在线更新功能
  cdn-prefix: https://cdn.jsdelivr.net/npm # CDN 前缀 (例如: https://cdn.jsdelivr.net/npm |  https://cdn.jsdmirror.com/npm（国内）)
